# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FOoAFhO3GLtNEezpN85jUlUX8_kfHpZq
"""

# Importing the random module to generate random numbers
import random

def roll_dice(num_dice, num_sides):
    rolls = [] # Initialize an empty list to store the result of each roll

    for _ in range(num_dice):  # Loop through each die to roll
        roll_result = random.randint(1, num_sides)  #Generate a random number between 1 and 'num_sides'
        rolls.append(roll_result)  # Append the result to the rolls list
    return rolls

def main():
    while True: # Infinite loop to keep the program running until the user decides to quit
        num_dice = int(input("Enter the number of dice to roll: ")) # Prompt the user to enter the number of dice
        num_sides = int(input("Enter the number of sides for each die: ")) # Prompt the user to enter the number of sides for each die
        if num_dice <= 0 or num_sides <= 0:  # Check if either input is less than or equal to zero
            print("Please enter valid values (greater than zero) for both number of dice and number of sides.")
            continue # Continue to the beginning of the loop to prompt the user again
        else:
            rolls = roll_dice(num_dice, num_sides) # Call the roll_dice function to simulate rolling the dice
            print("Results of rolling {} dice with {} sides each:".format(num_dice, num_sides))
            print("Rolls:", rolls) # Print the result of each roll
        play_again = input("Do you want to roll again? (yes/no): ") # Ask the user if they want to roll again
        if play_again.lower() != "yes":  # Check if the user's input is not 'yes'
            print("Thank you for using the Dice Rolling Simulator!")
            break  # Exit the loop and end the program

if __name__ == "__main__":
    main()